{"name": "test_4", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 4", "trace": "def test_4():\n        print(\"test_4\")\n>       assert 1 == 4\nE       assert 1 == 4\n\n..\\test_case\\test_case_02.py:3: AssertionError"}, "attachments": [{"name": "stdout", "source": "8a66181f-ac48-49db-bcb8-1d441ac87a7c-attachment.txt", "type": "text/plain"}], "start": 1607077082213, "stop": 1607077082215, "uuid": "e2118a9a-6791-4e5c-aecf-8bdff5f72e9c", "historyId": "2f847e93cec3be246e1f2e9c40e99306", "testCaseId": "3981143484eba921566f524e5115510d", "fullName": "test_case.test_case_02#test_4", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_case_02"}, {"name": "host", "value": "LAPTOP-UDME04BU"}, {"name": "thread", "value": "20728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_case_02"}]}